formspree:
  method: post
  action: https://formspree.io/f/mvonvydw
maps_embed_api:
  host: www.google.com
  resource: /maps/embed/v1/view
  center:
    latitude: 51.507584
    longitude: 0.062660
  zoom: 12